[versions]
agp = "8.8.0"
appcompatVersion = "1.6.1"
core = "1.58.0.0"
jj2000 = "5.2"
jmrtd = "0.7.18"
jp2Android = "1.0.3"
jpeg2000Decoder = "1.1.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
material = "1.12.0"
materialVersion = "1.9.0"
opencv = "4.8.0"
scubaScAndroid = "0.0.20"
cameraCore = "1.5.2"
cameraView = "1.5.2"
cameraLifecycle = "1.5.2"

[libraries]
appcompat-v161 = { module = "androidx.appcompat:appcompat", version.ref = "appcompatVersion" }
core = { module = "com.madgag.spongycastle:core", version.ref = "core" }
jj2000 = { module = "com.github.mhshams:jj2000", version.ref = "jj2000" }
jmrtd = { module = "org.jmrtd:jmrtd", version.ref = "jmrtd" }
jp2-android = { module = "com.gemalto.jp2:jp2-android", version.ref = "jp2Android" }
jpeg2000-decoder = { module = "com.github.ThalesGroup.Android-Image-Segmenter:jpeg2000-decoder", version.ref = "jpeg2000Decoder" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
material-v190 = { module = "com.google.android.material:material", version.ref = "materialVersion" }
opencv = { module = "org.opencv:opencv", version.ref = "opencv" }
prov = { module = "com.madgag.spongycastle:prov", version.ref = "core" }
scuba-sc-android = { module = "net.sf.scuba:scuba-sc-android", version.ref = "scubaScAndroid" }
camera-core = { group = "androidx.camera", name = "camera-core", version.ref = "cameraCore" }
camera-view = { group = "androidx.camera", name = "camera-view", version.ref = "cameraView" }
camera-lifecycle = { group = "androidx.camera", name = "camera-lifecycle", version.ref = "cameraLifecycle" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

